apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marathonrunner-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marathonrunner-operator.labels" . | nindent 4 }}
    control-plane: {{ include "marathonrunner-operator.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "marathonrunner-operator.selectorLabels" . | nindent 6 }}
      control-plane: {{ include "marathonrunner-operator.fullname" . }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "marathonrunner-operator.selectorLabels" . | nindent 8 }}
        control-plane: {{ include "marathonrunner-operator.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "marathonrunner-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: {{ include "marathonrunner-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
            - --health-probe-bind-address=:8081
          ports:
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: {{ .Values.healthProbe.livenessInitialDelay }}
            periodSeconds: {{ .Values.healthProbe.livenessPeriod }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: {{ .Values.healthProbe.readinessInitialDelay }}
            periodSeconds: {{ .Values.healthProbe.readinessPeriod }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
