apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marathonrunner-operator-role
rules:
  - apiGroups:
      - marathonrunner.io
    resources:
      - testruns
      - testruns/status
      - testruns/finalizers
      - performancetests
      - performancetests/status
      - performancetests/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
